### ISSUE TITLE
Source for most recent post

### ISSUE THREAD

**Issue by brandonwillard** [josephwillard/josephwillard.github.io#2]
Where's the `.org` file for the [most recent post](https://josephwillard.github.io/converting-pymc4-to-symbolic-pymc-continued.html)?

**Comment by josephwillard** [comment]
All org files are located on the source_code branch in the folder `org_files`.

**Comment by brandonwillard** [comment]
And which one is the most recent post (that was the question)?  The naming and multitude of files is extremely confusing.

**Comment by josephwillard** [comment]
Cleaned up the folder structure and renamed the files to be more clear. The file related to the recent post is "convert_pymc4_to_symbolic-pymc_continued.org".
